name: shall
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - images/
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Bold.ttf
          weight: 800
        - asset: fonts/Rubik-Italic.ttf
          style: italic
        - asset: fonts/Rubik-Light.ttf
          weight: 100
        - asset: fonts/Rubik-Medium.ttf
          weight: 300
        - asset: fonts/Rubik-Regular.ttf
          weight: 500
    - family: Coolvetica
      fonts:
        - asset: fonts/coolvetica_compressed_hv.otf
          weight: 800
        - asset: fonts/coolvetica_condensed_rg.otf
          weight: 300
        - asset: fonts/coolvetica_crammed_rg.otf
          weight: 100
        - asset: fonts/coolvetica_rg_it.otf
          style: italic
        - asset: fonts/coolvetica_rg.otf
          weight: 500
  uses-material-design: true